### ISSUE TITLE
Uncaught ReferenceError: TANAGURU_MODULES is not defined

### ISSUE THREAD

**Issue by pbq** [Tanaguru/tanaguru2020-webapp#101]
Bonjour, suite au déploiement des images tanaguru-rest et tanaguru-webapp en version 1.0.3,
nous rencontrons l'erreur suivante sur accès à la page d'accueil.

Après vérification il s’avère que la variable TANAGURU_MODULES n'est pas renseignée dans le conteneur webapp.

Pourriez-vous nous indiquer ce qui manque pour la valorisation de cette variable ?

Merci.
Pierre

**Comment by fhalna** [comment]
Can't repro
