### ISSUE TITLE
Environnement

### ISSUE THREAD

**Issue by jpboignard** [Tanaguru/tanaguru2020-webapp#182]
Bonjour,
j'essaie d'installer en local WSL2 sans succès.
npm install > nombreux warn deprecated 
erreurs gyp et g++ , apparemment liées à node_modules/node-sass

Quelles sont les versions npm / node / python / ...  en prérequis ? 
Merci

**Comment by severineFF-tanaguru** [comment]
Bonjour,
Voici les prérequis : 
- python 2
- node 14
- npm 6
