### ISSUE TITLE
[PROPOSAL] augmentation de la longueur d'un projet et alerte dépassement

### ISSUE THREAD

**Issue by pbq** [Tanaguru/tanaguru2020-webapp#84]
La longueur d'un projet est limitée à 30 caractères maximum.

Serait-il possible d'une part d'augmenter cette limitation ?

D'autre part, serait-il possible de rajouter un message d'alerte indiquant ce dépassement ? 
Actuellement, le message `An error has occured` apparaît.

Pierre

**Comment by lpedrau** [comment]
- Augmentation de la taille du nom d'un projet à 50 caractères.
- Ajout d'un message d'alerte précis.
